ShoppingProject/Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingProject.Models
{
    public class ApplicationUser : IdentityUser
    {
        public string User_Username { get; set; }

        public string ProfilePicture { get; set; }

        public string Bio { get; set; }

        public bool VerifiedAccout { get; set; }
    }
}

ShoppingProject/ViewModels/AccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingProject.ViewModels
{
    public class AccountViewModel
    {
        public string userId { get; set; }

        public string Username { get; set; }

        public string Photo { get; set; }

        public string Bio { get; set; }


    }

}

ShoppingProject/Controllers/ApplicationUserController.cs
using ShoppingProject.Models;
using ShoppingProject.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingProject.Data;

namespace ShoppingProject.Controllers
{
    public class ApplicationUserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly Microsoft.Extensions.Hosting.IHostingEnvironment _hostingEnvironment;


        public ApplicationUserController(UserManager<ApplicationUser> userManager, ApplicationDbContext context, RoleManager<IdentityRole> roleManager, Microsoft.Extensions.Hosting.IHostingEnvironment hostingEnvironment, SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _context = context;
            _roleManager = roleManager;
            _hostingEnvironment = hostingEnvironment;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        /*public async Task<IActionResult> Index(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            else
            {
                //var posts = _context.Posts.Where(x => x.UserId.Equals(id)).ToList();

                AccountViewModel model = new AccountViewModel
                {
                    userId = user.Id,
                    Username = user.User_Username,
                    Bio = user.Bio,
                    Photo = user.ProfilePicture,

                };
                return View(model);
            }
        }*/

        public async Task<IActionResult> Account(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            else
            {
                //var posts = _context.Posts.Where(x => x.UserId.Equals(id)).ToList();

                AccountViewModel model = new AccountViewModel
                {
                    userId = user.Id,
                    Username = user.User_Username,
                    Bio = user.Bio,
                    Photo = user.ProfilePicture,

                };
                return View(model);
            }
        }
    }
}

ShoppingProject/Views/ApplicationUser/Account.cshtml
  @using Microsoft.AspNetCore.Identity;
@model ShoppingProject.ViewModels.AccountViewModel

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Account";
    var ProfilePicture = "~/images/" + Model.Photo;
    var user = await UserManager.GetUserAsync(User);
}

@section Styles {
    <link href="~/css/UserProfile.css" rel="stylesheet" />
}


<div class="user-profile-main">
    <img src="@ProfilePicture" alt="Alternate Text" asp-append-version="true" />
    <h1>@Model.Username</h1>
</div>

<div class="user-bio">
    @if (Model.Bio.Equals(""))
    {
        <p>No Bio yet. :/</p>


    }
    else
    {
        <p>@Model.Bio</p>

    }
</div>

@if (SignInManager.IsSignedIn(User))
{
    <div class="delete-account">
        @if (user.Id.Equals(Model.userId))
        {
            <a asp-action="DeleteAccount" asp-controller="ApplicationUser" asp-route-id="@Model.userId" class="btn">Delete</a>
        }
        else if (User.IsInRole("Admin"))
        {
            <a asp-action="DeleteAccount" asp-controller="ApplicationUser" asp-route-id="@Model.userId" class="btn">Delete</a>
        }
    </div>
}

ShoppingProject/Views/ApplicationUser/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model ShoppingProject.ViewModels.AccountViewModel

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Account";
    var ProfilePicture = "~/images/" + Model.Photo;
    var user = await UserManager.GetUserAsync(User);
}

@section Styles {
    <link href="~/css/UserProfile.css" rel="stylesheet" />
}


<div class="user-profile-main">
    <img src="@ProfilePicture" alt="Alternate Text" asp-append-version="true" />
    <h1>@Model.Username</h1>
</div>

<div class="user-bio">
    @if (Model.Bio.Equals(""))
    {
        <p>No Bio yet. :/</p>


    }
    else
    {
        <p>@Model.Bio</p>

    }
</div>

@if (SignInManager.IsSignedIn(User))
{
    <div class="delete-account">
        @if (user.Id.Equals(Model.userId))
        {
            <a asp-action="DeleteAccount" asp-controller="ApplicationUser" asp-route-id="@Model.userId" class="btn">Delete</a>
        }
        else if (User.IsInRole("Admin"))
        {
            <a asp-action="DeleteAccount" asp-controller="ApplicationUser" asp-route-id="@Model.userId" class="btn">Delete</a>
        }
    </div>
}