ShoppingProject/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ShoppingProject.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }

        // GET: About/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: About/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: About/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: About/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: About/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: About/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: About/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ShoppingProject/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ShoppingProject.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        // GET: Contact/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contact/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contact/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Contact/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Contact/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ShoppingProject/Controllers/HomeController.cs
using ShoppingProject.Data;
using ShoppingProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ShoppingProject.Data;
using ShoppingProject.Models;

namespace OneStopBuy.Controllers
{

    /*[Authorize(Roles = "Admin")]*/
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public readonly ApplicationDbContext _context;
        public readonly UserManager<ApplicationUser> _userManager;
        public HomeController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, ILogger<HomeController> logger)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
        }
        public async Task<IActionResult> IndexMessage()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUserName = currentUser.UserName;
            }
            var messages = await _context.Messages.ToListAsync();
            return View(messages);
        }

        public async Task<IActionResult> CreateMessage(Message message)
        {
            if (ModelState.IsValid)
            {
                message.UserName = User.Identity.Name;
                var sender = await _userManager.GetUserAsync(User);
                message.UserID = sender.Id;
                await _context.Messages.AddAsync(message);
                await _context.SaveChangesAsync();
                return RedirectToAction("IndexMessage");
            }
            return Error();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        /*public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }*/
        /*[AllowAnonymous]*/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NewsUpload()
        {
            return View();
        }

        public IActionResult allNews()
        {
            return View();
        }

        public IActionResult NewsReports()
        {
            var users = _userManager.Users;
            return View(users);
        }


        /* [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
         public IActionResult Error()
         {
             return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
         }*/
    }
}

ShoppingProject/Views/Home/Index.cshtml
@model ShoppingProject.Models.News
@{
    ViewData["Title"] = "Home Page";
}
<div class="home-background">
    <div class="container">
        <div class="banner-info-bg">
            <h5>Find the best deals<br /> and everything you need for school!</h5>
            <div class="banner-buttons mt-4">
                <a class="btn btn-style btn-primary" asp-area="" asp-controller="About" asp-action="Index">Read More</a>
            </div>
        </div>
    </div>
</div>



<section class="w3l-content-3">
    <div class="content-3-mian py-5">
        <div class="container py-lg-5">
            <div class="content-info-in row">
                <div class="col-lg-6">
                    <img src="~/img/items.jpg" alt="" class="img-fluid">
                </div>
                <div class="col-lg-6 mt-lg-0 mt-5 about-right-faq align-self  pl-lg-5">
                    <div class="title-content text-left mb-2">
                        <h6 class="sub-title">Who We Are</h6>
                        <h3 class="hny-title">
                            A store for every student needs!
                        </h3>
                    </div>
                    <p class="mt-3">
                        Lorem ipsum viverra feugiat. Pellen tesque libero ut justo,
                        ultrices in ligula. Semper at tempufddfel. Lorem ipsum dolor sit amet consectetur
                        adipisicing
                        elit.fugiat consequatur voluptatem nihil ad.Lorem illum facere aperiam consectetur adipisicing.
                    </p>
                    <a asp-area="" asp-controller="About" asp-action="Index" class="btn btn-style btn-primary mt-md-5 mt-5">Read More</a>
                </div>
            </div>
        </div>

    </div>
</section>


<section class="features-4">
    <div class="features4-block py-5">
        <div class="container py-lg-4">
            <div class="title-content text-center mb-lg-5 mt-4">
                <h6 class="sub-title">Why Choose Us</h6>
                <h3 class="hny-title">Great Product service</h3>
                <p class="fea-para">Lorem illum facere aperiam consectetur adipisicing elit</p>
            </div>
            <div class="row features4-grids text-left mt-lg-4">
                <div class="col-lg-3 col-md-6 features4-grid mt-4">
                    <div class="features4-grid-inn">
                        <div class="img-featured">
                            <div class="ch-item ch-img-1">
                                <div class="ch-info-wrap">
                                    <div class="ch-info">
                                        <div class="ch-info-front ch-img-1"></div>
                                        <div class="ch-info-back">
                                            <h4>Toddler</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="features4-rightinfo">
                            <h5><a href="#URL">Toddler / 2 Years</a></h5>
                            <p>Lorem ipsum dolor sit amet,Ea consequuntur illum facere.</p>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 features4-grid mt-4">
                    <div class="features4-grid-inn">
                        <div class="img-featured">
                            <div class="ch-item ch-img-2">
                                <div class="ch-info-wrap">
                                    <div class="ch-info">
                                        <div class="ch-info-front ch-img-2"></div>
                                        <div class="ch-info-back">
                                            <h4>1st Grade</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="features4-rightinfo">
                            <h5>
                                <a href="#URL">
                                    6 Years / Grade 1
                                </a>
                            </h5>
                            <p>Lorem ipsum dolor sit amet,Ea consequuntur illum facere.</p>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 features4-grid mt-4">
                    <div class="features4-grid-inn">
                        <div class="img-featured">
                            <div class="ch-item ch-img-3">
                                <div class="ch-info-wrap">
                                    <div class="ch-info">
                                        <div class="ch-info-front ch-img-3"></div>
                                        <div class="ch-info-back">
                                            <h4>6th Grade</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="features4-rightinfo">
                            <h5>
                                <a href="#URL">
                                    11 Years / Grade 6
                                </a>
                            </h5>
                            <p>Lorem ipsum dolor sit amet,Ea consequuntur illum facere.</p>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 features4-grid mt-4">
                    <div class="features4-grid-inn">
                        <div class="img-featured">
                            <div class="ch-item ch-img-4">
                                <div class="ch-info-wrap">
                                    <div class="ch-info">
                                        <div class="ch-info-front ch-img-4"></div>
                                        <div class="ch-info-back">
                                            <h4>8th  Grade</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="features4-rightinfo">
                            <h5>
                                <a href="#URL">
                                    Teens / Grade 8+
                                </a>
                            </h5>
                            <p>Lorem ipsum dolor sit amet,Ea consequuntur illum facere.</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="middle py-5">
    <div class="container py-xl-5 py-lg-3">
        <div class="welcome-left text-left py-3">
            <div class="title-content">
                <h6 class="sub-title">Call Us</h6>
                <h3 class="hny-title two mb-2">Imagine Your Product Feeling New Again</h3>
                <p>
                    Questions? Give us a call today at <a href="tel:+(21) 255 999 8899">
                        +(383)
                        49 100 101
                    </a>
                </p>

            </div>

            <a asp-area="" asp-controller="Services" asp-action="Index" class="btn btn-white mt-md-5 mt-4 mr-sm-2">Our Services</a>
            <a asp-area="" asp-controller="Contact" asp-action="Index" class="btn btn-white-active btn-primary mt-md-5 mt-4">Contact Us</a>
        </div>
    </div>
</div>

<section class="w3l-testimonials">
    <div class="container text-center mt-5">
        <div class="title-content text-center mb-lg-5 mb-4">
            <h6 class="sub-title">You're in the right place</h6>
            <h3 class="hny-title">Are you looking for a Product?</h3>

        </div>

    </div>
</section>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script type='text/javascript'>
    function ajaxGet() {

        $.ajax({
            type: "GET",
            url: "http://localhost:3000/user/allNews",
            success: function (result) {


                $.each(result, function (key, value) {

                    console.log(result[key].image);
                });
                $.each(result, function (index, obj) {
                    var tr = $("<div class='w-75 p-3 mx-auto border'></div>");

                    tr.append("<br><h3 class='text-center text-dark'>" + obj.title + "</h3><hr>");
                    tr.append("<p class='text-center text-dark'>" + obj.description + "</p>");
    @*tr.append("<p style:'display:none'>" + obj.img_path + "</p>");*@
                        tr.append("<p>" + obj.createdAt + "</p><hr>");
                    tr.append("<button class='btn btn-warning btn-lg btn-block text-center text-dark' value=" + obj._id + " onclick=showReportWindow(this)>Report</button><hr>");

                    $("#contain").append(tr);
                });
    @*if (results.length > 0) {
                    $('#title').text(result[0].title);
                    $('#description').text(result[0].description);
                    $('#img_path').text(result[0].img_path);
                    }
                    else {
                    alert("No data.");
                    }*@
                    console.log("Success: ", result);
            },
            error: function (e) {
                $("#getResultDiv").html("Error");
                console.log("ERROR: ", e);
            }
        });
    }

    function showReportWindow(data) {
        var id = $(data).val();
        var element = $("<form method='POST' class='d-flex flex-column' ></form>");


        element.append("<h4>" + id + "</h4>");
        //element.append("<input placeholder='Report Reason'></input>");

        var select = $("<select class='mb-3 mt-3'></select>")


        select.append("<option>Uncivil, rude or vulgar</option>")
        select.append("<option>Discrimination</option>")
        select.append("<option>Public shaming</option>")
        select.append("<option>Over-posting</option>")
        select.append("<option>Conflict of interest</option>")
        element.append(select)
        element.append("<button type='button' value=" + id + " class='btn btn-danger' onclick='reportNews(this);'>Create Report</input>");

        $("#reportWindow").append(element);

        $("#reportWindow").css({ "opacity": "100%", "pointer-events": "all", "z-index": 1, "border": "2px solid black;" });

        //opacity: 0;
        //pointer - events: none;
        //z - index: 0;
    }

    function reportNews(data) {
        var id = $(data).val();
        var select = $("select :selected").val();
        console.log(id, select);
        var obj = {
            newsId: id,
            reportReason: select
        }
        $.ajax({
            type: "POST",
            url: 'http://localhost:3000/user/report_news/' + id,
            data: obj,
            dataType: "json",
            encode: true,
            success: function (result) {
                console.log(result);
                //location.reload(true);
                $("#reportWindow").css({ "opacity": "0", "pointer-events": "none", "z-index": -1 });
                $('form').remove();
            }
        });


    }

    function removenews(data) {
        var id = $(data).val();
        console.log(id);
        $.ajax({
            type: "DELETE",
            url: 'http://localhost:3000/user/remove_news/' + id,
            success: function (result) {
                console.log(result);
                location.reload(true);
            }
        });
    }
</script>

<style>
    #reportWindow {
        position: absolute;
        background: white;
        display: grid;
        align-items: center;
        width: 100%;
        height: 350px;
        margin-left: 14%;
        margin-top: 20px;
        box-shadow: 5px 5px 5px 8px gray,5px 10px 10px 8px gray,5px 15px 15px 8px lightgray;
        pointer-events: none;
        z-index: 0;
        transition: opacity 0.2s;
        border: 2px solid black;
    }

        #reportWindow form {
            width: 70%;
            margin-left: auto;
            margin-right: auto;
        }

    #smslogo {
        position: fixed;
        right: 133px;
        bottom: 51px;
        z-index: 500;
        width: 18px;
    }

    .fa-comment-dots {
        width: 100px;
    }

    * {
        box-sizing: border-box;
    }

    .left-side img {
        width: 350px;
    }

    .right-side {
        float: right;
    }

        .right-side p {
            min-width: 150px;
        }

    #reportWindow {
        position: absolute;
        background: white;
        display: flex;
        align-items: center;
        width: 75%;
        height: 350px;
        opacity: 0;
        pointer-events: none;
        z-index: 0;
        transition: opacity 0.2s;
    }

    @@media screen and (max-width: 1213px) {
        .right-side {
            float: right;
        }
    }

    @@media screen and (max-width: 770px) {
        .left-side {
            margin: 0 auto;
        }

        .right-side {
            text-align: center;
        }
    }

    @@media screen and (max-width: 365px) {
        .left-side img {
            width: 250px;
            margin: 0 auto;
            min-width: 200px;
        }
    }

    #app {
        background-color: lightgray;
    }
</style>

ShoppingProject/Views/Home/IndexMessage.cshtml
@model IEnumerable<ShoppingProject.Models.Message>
<br />
<br />
<br />
<br />
<br />
<br />
<h2 class="text-center text-primary">
    <i class="fab fa-facebook-messenger"></i>&nbsp; Ask for help

</h2>
<p style="text-align:center;">We will respond as fast as we can.</p>
<div id="Chats">
</div>
<div id="Chat">

    <input type="text" id="name" value="@ViewBag.CurrentUserName" />
    <input type="text" id="inputText" placeholder="Type here..." />

    <button type="submit" value="Send" id="SendMessageButton"><i class="far fa-paper-plane"></i></button>
</div>

@section scripts {
    <script src="~/signalr/signalr.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/js/chat.js"></script>

}

<style>
    input#name {
        display: none;
    }

    input#inputText {
        margin-top: 4px;
        width: 94%;
        border-radius: 25px;
        text-align: center;
    }

    div#Chat {
        width: 50%;
        margin-left: auto;
        margin-right: auto;
        height: 37px;
        margin-bottom: 50px;
    }

    div#Chats {
        width: 50%;
        margin-left: auto;
        margin-right: auto;
        background-color: lightgray;
        text-align: center;
        min-height: 130px;
        border-radius: 25px;
    }

    .fixed-top {
        background-color: seagreen;
    }

    div#Chats p {
        background-color: white;
        width: 70%;
        text-align: center;
        margin-left: auto;
        border-top-right-radius: 20px;
        border-top-left-radius: 20px;
        color: white;
        margin-right: auto;
        padding-top: 19px;
        background-color: royalblue;
    }

    div#Chats h4 {
        background-color: royalblue;
        width: 70%;
        color: white;
        text-align: center;
        margin-left: auto;
        margin-right: auto;
        margin-bottom: 16px;
        border-bottom-right-radius: 20px;
        border-bottom-left-radius: 20px;
    }

    button#SendMessageButton {
        border-radius: 25px;
    }
</style>

ShoppingProject/Views/Home/NewsReports.cshtml
@model IEnumerable<ApplicationUser>
<link rel=”stylesheet” href=” sweetalert.css”>
<div id="app">

    <br />
    <br />
    <br />
    <br />
    <br />

    <table class="table">
        <thead>
            <tr>
                <th>
                    Reason
                </th>
                <th>
                    News Id
                </th>
            </tr>

        </thead>
        <tbody>
            <tr v-for="report in allNewsReports" :key="report._id">
                <td>
                    <p>{{report.reportReason}}</p>
                </td>
                <td>
                    <p>{{report._id}}</p>
                </td>
                <td>
                    <button class="btn btn-danger" value="{{report._id}}" v-on:click="removeReport(report._id)">REMOVE</button>
                </td>
            </tr>
        </tbody>
    </table>

</div>


<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>



<script>
    // import Swal from 'sweetalert2/dist/sweetalert2.js'

    let app = new Vue({
        el: '#app',
        data: {
            allNewsReports: '',
        },
        mounted: function () {
            axios.get('http://localhost:3000/user/getNewsReports')
                .then(reports => {
                    this.allNewsReports = reports.data
                })
                .catch(err => {
                    console.log(err)
                })
        },
        methods: {
            removeReport: function (id) {
                console.log("TEST", id)
                axios.delete('http://localhost:3000/user/removeNewsReport/' + id)
                //swal("Your Report Is Deleted\nSuccessfully!", "success");
                Swal.fire(

                    'Your Report Is Deleted\nSuccessfully!',
                    'success',
                    function (isConfirm) {
                        if (isConfirm) {

                            location.reload(true);

                        }
                    }
                )
                location.reload(true);
                //alert("Your Report Is Deleted\nSuccessfully!");

            }
        }
    })
</script>

ShoppingProject/Views/Home/NewsUpload.cshtml
@{
    Layout = "~/Views/Shared/Admin.cshtml";
}

<div class="container">
    <div class="News">
        <h1 class="title">Create News</h1>
        <form id="form" method="POST" enctype="multipart/form-data">
            <input id="title" type="text" placeholder="Title" required /><br />
            @* <input id="description" type="text" placeholder="Description" required /><br />*@
            <input class="description" id="description" type="text" placeholder="Description" required /><br />
            <input type="file" name="image" id="fileUpload" required /><br />
            <button type="submit" style="width:70%" class="btn btn-success">Submit</button>
            <a class="nav-link text-dark mb-3" asp-area="" asp-controller="Home" asp-action="allNews">All News</a>
        </form>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("input").change(function (e) {

        for (var i = 0; i < e.originalEvent.srcElement.files; i++) {

            var file = e.originalEvent.srcElement.files[i];

            var img = document.createElement("img");
            var reader = new FileReader();
            reader.onloadend = function () {
                img.src = reader.result;
            }
            reader.readAsDataURL(file);
            $("input").after(img);
        }
    });
    var formData = new FormData();

    $('form').submit((e) => {
        jQuery.each(jQuery('#fileUpload')[0].files, function (i, file) {
    @*        formData.append('file', file);*@
                formData.set('file', file);

        });
        $.ajax({
            type: 'POST',
            url: 'http://localhost:3000/user/createPhoto',
            data: formData,
            contentType: false,
            processData: false,
            success: function (result) {
                if (result.status != 0) {
                    const newsData = {
                        title: $("#title").val(),
                        description: $("#description").val(),
                        img_path: result.file.filename
                    };


                    //console.log(result.file.filename)

                    $.ajax({
                        type: 'POST',
                        url: 'http://localhost:3000/user/createNews',
                        data: newsData,
                        dataType: "json",
                        encode: true,
                        success: function (result) {
                            if (result.status != 0) {
                                console.log(result);
    @* alert("Created Successfully");*@
                                    Swal.fire(
                                        'Created Successfully',
                                        'Click OK to continue!'

                                    )

                                return
                            }
                            location.reload(true);
                            console.log(result)

                        }
                    });
                }
            }
        });

        e.preventDefault();
    @*location.reload(true);*@
    @*alert("News was uploaded successfully "+location.reload(true));*@
    @*alert(location.hostname);*@
      })

</script>
<style>
    h1.title {
        text-align: center;
        padding-top: 23px;
    }

    .News {
        box-shadow: 3px 3px 5px #aaaaaa;
        border: 1px dotted #000000;
        border-radius: 5px;
        width: 100%;
        height: 50%;
        margin-top: 113px;
    }

    form {
        border-radius: 5px;
        text-align: center;
    }

    input#title {
        width: 70%;
        border-radius: 5px;
        height: 40px;
        border: 1px solid lightgray;
        margin-top: 32px;
        text-align: center;
    }

    .description {
        width: 70%;
        border-radius: 5px;
        height: 40px;
        border: 1px solid lightgray;
        margin-top: 32px;
        text-align: center;
    }

    input#fileUpload {
        cursor: pointer;
        width: 70%;
        height: 30px;
        border-radius: 5px;
        background-color: white;
        margin-top: 32px;
        text-align: center;
    }

    button {
        width: 60%;
        margin-top: 32px;
        margin-bottom: 32px;
        height: 40px;
        border-radius: 25px;
        background-color: lightgreen;
    }
</style>